### PR TITLE
naga 0.14

### PR DESCRIPTION
**Pull request by robtfm**
update to naga 0.14

### CODE REVIEW

**Comment by torokati44** [comment]
FYI, https://github.com/gfx-rs/wgpu/issues/4569 got fixed - even though no new release yet with it in.

**Comment by torokati44** [comment]
With https://github.com/gfx-rs/wgpu/issues/4569 merged, I think this should be unblocked now.

**Comment by robtfm** [comment]
i'll update once it's backported to 0.14.x and released, last i heard that will be this weekend

**Comment by torokati44** [comment]
Welp, no release happened last weekend.
But since then, a backport of that fix was merged: https://github.com/gfx-rs/wgpu/pull/4693

**Comment by torokati44** [comment]
Aand wgpu 0.18.1 is out! 😊

**Review by superdump — APPROVED** [review]

**Pull request merged**
