### PR TITLE
Correct atomic mapping

### PR DESCRIPTION
**Pull request by Joeoc2001**
Addresses #48

### CODE REVIEW

**Comment by robtfm** [comment]
this looks good.

would you mind adding your example from the issue as a test? i can do it if you don't have time.

**Review by JMS55 — APPROVED** [review]

**Comment by robtfm** [comment]
the test showed an issue with naga's autogenerated exchange result struct which i've added a fix for (in [8b3abfd](https://github.com/bevyengine/naga_oil/pull/49/commits/8b3abfda055ffba3c9cecb22064e7f16ff5ef257)).

unforunately it looks like we can't run the test on gpu on github's windows runners as hlsl is being used, and hlsl atomic ops are not supported in wgpu.

i've run it locally and it works as expected, and the output source looks fine so i've just commented out the gpu test. i think this is fine for now.

**Comment by mockersf** [comment]
> @mockersf - requesting your review mainly for the hlsl hack, in case you have a better idea.

Not really 🙁 
It would be nice to be able to link to an issue on Naga for the fix, but I couldn't find one

**Comment by robtfm** [comment]
@JMS55 are you using this? if so could you please review?

**Review by JMS55 — APPROVED** [review]
Not very familiar with naga_oil internals, but I've been using it and afaik it's fine, and the tests look good to me.

**Pull request merged**
